apiVersion: v1
kind: Pod
metadata:
  name: pod-config-volume
spec:
  containers:
  - name: test-container
    image: wangyanglinux/myapp:v1
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "cat /etc/config/special.how"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never
