apiVersion: v1
kind: Pod
metadata: 
  name: liveness-httpget-pod
spec: 
  containers: 
  - name: liveness-httpget-pod
    image: wangyanglinux/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    livenessProbe:
      httpGet:
        port: 80
        path: /index.html
      initialDelaySeconds: 1
      periodSeconds: 3
      timeoutSeconds: 10
